# hugo server --disableFastRender --baseURL=http://0.0.0.0:1313

title: YCC实验 - 2020
description: YCC编译原理实验 - 2020年春
theme: book
baseURL: https://yan-lang.github.io/ycc/docs

# Book configuration
disablePathToLower: true
enableGitInfo: true

publishDir: ../docs

# Needed for mermaid/katex shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
  highlight:
    guessSyntax: true
    style: xcode
    tabWidth: 4

# Multi-lingual mode config
# There are different options to translate files
# See https://gohugo.io/content-management/multilingual/#translation-by-filename
# And https://gohugo.io/content-management/multilingual/#translation-by-content-directory

DefaultContentLanguage: cn

languages:
  cn:
    languageName: 简体中文
    contentDir: content
    weight: 1
  # en:
  #   languageName: English
  #   contentDir: content.en
  #   weight: 2

menu:
  # before: []
  after:
    - name: "Submit"
      url: "https://zeqianglai.cn"
      weight: 6
    - name: "Github"
      url: "https://github.com/yan-lang/ycc"
      weight: 8
    - name: "Yan.io"
      url: "https://yan-lang.github.io/"
      weight: 10

params:
  # (Optional, default true) Controls table of contents visibility on right side of pages.
  # Start and end levels can be controlled with markup.tableOfContents setting.
  # You can also specify this parameter per page in front matter.
  BookToC: true

  # (Optional, default none) Set the path to a logo for the book. If the logo is
  # /static/logo.png then the path would be logo.png
  # BookLogo: /logo.png

  # (Optional, default none) Set leaf bundle to render as side menu
  # When not specified file structure and weights will be used
  # BookMenuBundle: /menu

  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to '*' to render all sections to menu
  BookSection: '*'

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo: https://github.com/yan-lang/ycc/

  # Enable "Edit this page" links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # Path must point to 'content' directory of repo.
  # BookEditPath: edit/master/exampleSite/content

  # Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat: "Jan 2, 2006"

  # (Optional, default true) Enables search function with flexsearch,
  # Index is built on fly, therefore it might slowdown your website.
  BookSearch: true

  # (Optional, default true) Enables comments template on pages
  # By default partals/docs/comments.html includes Disqus template
  # See https://gohugo.io/content-management/comments/#configure-disqus
  # Can be overwritten by same param in page frontmatter
  BookComments: true
